-- Create app user (run as SYS/SYSTEM in container init)
-- gvenzl/oracle-* images run scripts in /container-entrypoint-initdb.d as SYS.

ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER chatapp IDENTIFIED BY chatapp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 AND SQLCODE != -01921 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO chatapp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01919 THEN
      RAISE;
    END IF;
END;
/

ALTER SESSION SET CURRENT_SCHEMA = chatapp;

-- USERS
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE users (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR2(255) NOT NULL,
      login_name VARCHAR2(80) NOT NULL,
      password_hash VARCHAR2(255) NOT NULL,
      display_name VARCHAR2(120) NOT NULL,
      avatar_url VARCHAR2(500),
      is_active NUMBER(1) DEFAULT 1 NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX users_uq_email ON users(email)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX users_uq_login_name ON users(login_name)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Friendships (undirected unique pair)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE friendships (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      requester_id NUMBER NOT NULL,
      recipient_id NUMBER NOT NULL,
      status VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES users(id),
      CONSTRAINT fk_friendships_recipient FOREIGN KEY (recipient_id) REFERENCES users(id),
      CONSTRAINT ck_friendships_status CHECK (status IN ('Pending','Accepted','Rejected'))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX friendships_uq_pair ON friendships(requester_id, recipient_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Conversations and members
-- Conversations
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE conversations (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type VARCHAR2(10) NOT NULL,
      name VARCHAR2(200),
      avatar_url VARCHAR2(500),
      -- Thêm cột last_message lưu trữ chuỗi JSON
      last_message VARCHAR2(4000),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT ck_conversations_type CHECK (type IN ('private','group')),
      -- Đảm bảo dữ liệu đưa vào phải đúng chuẩn JSON (Hỗ trợ Oracle 12c trở lên)
      CONSTRAINT ck_conversations_last_msg CHECK (last_message IS JSON)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE conversation_members (
      conversation_id NUMBER NOT NULL,
      user_id NUMBER NOT NULL,
      role VARCHAR2(20) DEFAULT 'member' NOT NULL,
      joined_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT pk_conversation_members PRIMARY KEY (conversation_id, user_id),
      CONSTRAINT fk_cm_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
      CONSTRAINT fk_cm_user FOREIGN KEY (user_id) REFERENCES users(id)
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

